-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 15:27:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veterinariadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veterinariadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veterinariadb` DEFAULT CHARACTER SET utf8 ;
USE `veterinariadb` ;

-- -----------------------------------------------------
-- Table `veterinariadb`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`nivel` (
  `idnivel` INT NOT NULL,
  `nivelUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `telefonosecundario` INT NULL,
  `nivelUsuario` VARCHAR(45) NULL,
  `fechaAlta` DATETIME NULL,
  `fotoPortada` BLOB NULL,
  `foto` BLOB NULL,
  `estado` INT NULL,
  `nivel_idnivel` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_nivel_idx` (`nivel_idnivel` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_nivel`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `veterinariadb`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`planvacunacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`planvacunacion` (
  `idplanvacunacion` INT NOT NULL,
  `vacuna1` VARCHAR(45) NULL,
  `vacuna2` VARCHAR(45) NULL,
  `vacuna3` VARCHAR(45) NULL,
  `vacuna4` VARCHAR(45) NULL,
  `vacuna5` VARCHAR(45) NULL,
  `fechaAlta` VARCHAR(45) NULL,
  `fechaActual` VARCHAR(45) NULL,
  PRIMARY KEY (`idplanvacunacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`HIstorialMedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`HIstorialMedido` (
  `idHIstorialMedido` INT NOT NULL,
  `diagnostico` VARCHAR(45) NULL,
  `hospitalizacion` VARCHAR(45) NULL,
  `fechaIngreso` DATETIME NULL,
  `fechaAlta` DATETIME NULL,
  `planvacunacion_idplanvacunacion` INT NOT NULL,
  PRIMARY KEY (`idHIstorialMedido`),
  INDEX `fk_HIstorialMedido_planvacunacion1_idx` (`planvacunacion_idplanvacunacion` ASC) VISIBLE,
  CONSTRAINT `fk_HIstorialMedido_planvacunacion1`
    FOREIGN KEY (`planvacunacion_idplanvacunacion`)
    REFERENCES `veterinariadb`.`planvacunacion` (`idplanvacunacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`pacientes` (
  `idpacientes` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `raza` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `certificados` BLOB NULL,
  `foto` BLOB NULL,
  `usuario_idusuario` INT NOT NULL,
  `HIstorialMedido_idHIstorialMedido` INT NOT NULL,
  PRIMARY KEY (`idpacientes`),
  INDEX `fk_pacientes_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_pacientes_HIstorialMedido1_idx` (`HIstorialMedido_idHIstorialMedido` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `veterinariadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_HIstorialMedido1`
    FOREIGN KEY (`HIstorialMedido_idHIstorialMedido`)
    REFERENCES `veterinariadb`.`HIstorialMedido` (`idHIstorialMedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`cita` (
  `idcita` INT NOT NULL,
  `fechaAlta` DATETIME NULL,
  `fechaCita` DATETIME NULL,
  `pacientes_idpacientes` INT NOT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `fk_cita_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  CONSTRAINT `fk_cita_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `veterinariadb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`posteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`posteos` (
  `idposteos` INT NOT NULL,
  `fechaAlta` DATETIME NULL,
  `imagen` BLOB NULL,
  `texto` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idposteos`),
  INDEX `fk_posteos_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_posteos_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `veterinariadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`comentarios` (
  `idcomentarios` INT NOT NULL,
  `texto` VARCHAR(45) NULL,
  `fechaAlta` DATETIME NULL,
  `usuario_idusuario` INT NOT NULL,
  `posteos_idposteos` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_comentarios_posteos1_idx` (`posteos_idposteos` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `veterinariadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_posteos1`
    FOREIGN KEY (`posteos_idposteos`)
    REFERENCES `veterinariadb`.`posteos` (`idposteos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`productoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`productoServicio` (
  `idproductoServicio` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idproductoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`pedido` (
  `usuario_idusuario` INT NOT NULL,
  `productoServicio_idproductoServicio` INT NOT NULL,
  `cantidad` INT NULL,
  `fechaAlta` DATETIME NULL,
  PRIMARY KEY (`usuario_idusuario`, `productoServicio_idproductoServicio`),
  INDEX `fk_usuario_has_productoServicio_productoServicio1_idx` (`productoServicio_idproductoServicio` ASC) VISIBLE,
  INDEX `fk_usuario_has_productoServicio_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_productoServicio_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `veterinariadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_productoServicio_productoServicio1`
    FOREIGN KEY (`productoServicio_idproductoServicio`)
    REFERENCES `veterinariadb`.`productoServicio` (`idproductoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinariadb`.`PlanDesparacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinariadb`.`PlanDesparacitacion` (
  `idPlanDesparacitacion` INT NOT NULL,
  `21Dias` VARCHAR(45) NULL,
  `Semana5` VARCHAR(45) NULL,
  `Semana7` VARCHAR(45) NULL,
  `Semana9` VARCHAR(45) NULL,
  `3meses` VARCHAR(45) NULL,
  `4meses` VARCHAR(45) NULL,
  `5meses` VARCHAR(45) NULL,
  `cada 3 meses` VARCHAR(45) NULL,
  `fechaAlta` DATETIME NULL,
  `FechaActual` DATETIME NULL,
  `HIstorialMedido_idHIstorialMedido` INT NOT NULL,
  PRIMARY KEY (`idPlanDesparacitacion`),
  INDEX `fk_PlanDesparacitacion_HIstorialMedido1_idx` (`HIstorialMedido_idHIstorialMedido` ASC) VISIBLE,
  CONSTRAINT `fk_PlanDesparacitacion_HIstorialMedido1`
    FOREIGN KEY (`HIstorialMedido_idHIstorialMedido`)
    REFERENCES `veterinariadb`.`HIstorialMedido` (`idHIstorialMedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

